// Ported from bible-strong-avatar-lab —
// https://github.com/smontlouis/bible-strong-avatar-lab
// AGPL-3.0-only, © Stéphane Montlouis-Calixte. See THIRD_PARTY_NOTICES.md.
//
// GENERATED by Scripts/port_avatar_lab.py — do not edit by hand. The numbers
// are avatar-lab's calibration table and the derivation of the sequences from
// it is `createInitialSequences()` re-run; both come from that project, where
// they are measurements and authored choreography rather than settings. The
// mapping onto bloub's face lives in AvatarLabFace.swift, which is written by
// hand and is the only file allowed to interpret these numbers.

import Foundation

/// One of avatar-lab's expression presets, in avatar-lab's own units.
///
/// Carried verbatim rather than pre-converted, so a re-calibration upstream is
/// a re-run of the generator and nothing else. ``AvatarLabFace`` is what turns
/// one of these into a ``BloubExpression``, and it is the only place that is
/// allowed to know what the units mean.
public struct AvatarLabExpression: Sendable, Hashable, Identifiable {
    /// avatar-lab's own id, e.g. `expression-07`.
    public let id: String
    /// What the studio calls it, e.g. `angry-right`.
    public let semanticKey: String
    /// Head orientation in degrees: X pitches (positive looks up), Y yaws
    /// (positive looks right), Z rolls (positive drops the right side).
    public let headX: Double
    public let headY: Double
    public let headZ: Double
    /// Eye box, in avatar-lab face units — hundredths of its sphere's radius
    /// of 120, so 50 is an arc of 50/120 radians.
    public let widthLeft: Double
    public let widthRight: Double
    public let heightLeft: Double
    public let heightRight: Double
    /// The eyes' full separation, same units: each eye sits at ±spacing/2.
    public let spacing: Double
    public let positionXLeft: Double
    public let positionXRight: Double
    /// The pair's latitude on the sphere. Positive puts the eyes lower.
    public let positionYLeft: Double
    public let positionYRight: Double
    /// Each eye capsule's own rotation, degrees, positive = the top goes right.
    public let leftAngle: Double
    public let rightAngle: Double
    /// avatar-lab's projection strength. 1 throughout the bundled set, which
    /// is why this port has nothing to apply it to: bloub already narrows the
    /// far eye through the sphere's own depth factor.
    public let perspective: Double

    public init(
        id: String,
        semanticKey: String,
        headX: Double, headY: Double, headZ: Double,
        widthLeft: Double, widthRight: Double,
        heightLeft: Double, heightRight: Double,
        spacing: Double,
        positionXLeft: Double, positionXRight: Double,
        positionYLeft: Double, positionYRight: Double,
        leftAngle: Double, rightAngle: Double,
        perspective: Double
    ) {
        self.id = id
        self.semanticKey = semanticKey
        self.headX = headX
        self.headY = headY
        self.headZ = headZ
        self.widthLeft = widthLeft
        self.widthRight = widthRight
        self.heightLeft = heightLeft
        self.heightRight = heightRight
        self.spacing = spacing
        self.positionXLeft = positionXLeft
        self.positionXRight = positionXRight
        self.positionYLeft = positionYLeft
        self.positionYRight = positionYRight
        self.leftAngle = leftAngle
        self.rightAngle = rightAngle
        self.perspective = perspective
    }
}

/// Which family a sequence belongs to.
///
/// avatar-lab names them in French — `Cycle de vie` and `Réactions`;
/// the raw values keep those names so a sequence can be matched against the
/// studio without a translation table.
public enum AvatarSequenceGroup: String, Sendable, Hashable, CaseIterable {
    /// What an avatar does while nothing has happened to it.
    case lifeCycle = "Cycle de vie"
    /// A short thing that happens *to* an avatar and then stops.
    case reaction = "Réactions"
}

/// How a step arrives.
public enum AvatarSequenceCurve: String, Sendable, Hashable, CaseIterable {
    case spring
    case smooth
    case snappy
}

/// What happens when a sequence runs out of steps.
public enum AvatarSequencePlayback: String, Sendable, Hashable, CaseIterable {
    case loop
    case once
    case pingPong
}

/// One beat of a sequence: an expression, how it is reached, and how long it
/// is then held.
public struct AvatarSequenceStep: Sendable, Hashable {
    /// The ``AvatarLabExpression/id`` this step rests on.
    public let expressionID: String
    /// How long the step is held, seconds. avatar-lab stores milliseconds.
    public let hold: Double
    /// How long the morph into it takes, seconds.
    public let transition: Double
    public let curve: AvatarSequenceCurve

    public init(
        expressionID: String,
        hold: Double,
        transition: Double,
        curve: AvatarSequenceCurve
    ) {
        self.expressionID = expressionID
        self.hold = hold
        self.transition = transition
        self.curve = curve
    }
}

/// A sequence's own blink rhythm. Seconds, not milliseconds.
public struct AvatarBlinkRhythm: Sendable, Hashable {
    public let isEnabled: Bool
    public let initialDelay: Double
    public let minInterval: Double
    public let maxInterval: Double
    public let duration: Double

    public init(
        isEnabled: Bool,
        initialDelay: Double,
        minInterval: Double,
        maxInterval: Double,
        duration: Double
    ) {
        self.isEnabled = isEnabled
        self.initialDelay = initialDelay
        self.minInterval = minInterval
        self.maxInterval = maxInterval
        self.duration = duration
    }
}

/// One of avatar-lab's built-in animations.
public struct AvatarSequence: Sendable, Hashable, Identifiable {
    public let id: AvatarSequenceID
    public let group: AvatarSequenceGroup
    public let playback: AvatarSequencePlayback
    public let steps: [AvatarSequenceStep]
    public let blink: AvatarBlinkRhythm

    public init(
        id: AvatarSequenceID,
        group: AvatarSequenceGroup,
        playback: AvatarSequencePlayback,
        steps: [AvatarSequenceStep],
        blink: AvatarBlinkRhythm
    ) {
        self.id = id
        self.group = group
        self.playback = playback
        self.steps = steps
        self.blink = blink
    }

    /// The same sequence, played a different way.
    ///
    /// A life-cycle sequence loops; the choreographer plays some of them once
    /// as a reaction and needs to say so without a second copy of the data.
    public func played(_ mode: AvatarSequencePlayback) -> AvatarSequence {
        AvatarSequence(id: id, group: group, playback: mode, steps: steps, blink: blink)
    }
}

/// The built-in animations' ids, in avatar-lab's declaration order.
public enum AvatarSequenceID: String, Sendable, Hashable, CaseIterable {
    case sleeping
    case waking
    case idle
    case listening
    case thinking
    case searching
    case working
    case excited
    case surprised
    case suspicious
    case angry
    case drowsy
    case happy
    case curious
    case confused
    case bored
    case proud
    case shy
    case sad
    case laughing
    case scared
    case playful
    case celebrate
}

/// avatar-lab's bundled vocabulary, as data.
public enum AvatarLabPresets {
    /// The calibrated presets, in avatar-lab's own order — the index a
    /// ``statePools`` entry refers to is this array's index.
    public static let expressions: [AvatarLabExpression] = [
        AvatarLabExpression(
            id: "expression-00",
            semanticKey: "upward-side-glance",
            headX: 7.3, headY: 27.8, headZ: -16.1,
            widthLeft: 24.2, widthRight: 27.6,
            heightLeft: 38.9, heightRight: 40.7,
            spacing: 54.3,
            positionXLeft: 0, positionXRight: 0,
            positionYLeft: -20.5, positionYRight: -20.5,
            leftAngle: 0, rightAngle: 0,
            perspective: 1
        ),
        AvatarLabExpression(
            id: "expression-01",
            semanticKey: "downward-gaze",
            headX: -35.6, headY: 0.7, headZ: -8.5,
            widthLeft: 29.4, widthRight: 27.3,
            heightLeft: 49.5, heightRight: 49.8,
            spacing: 57.7,
            positionXLeft: 0, positionXRight: 0,
            positionYLeft: -42, positionYRight: -42,
            leftAngle: 0, rightAngle: 0,
            perspective: 1
        ),
        AvatarLabExpression(
            id: "expression-02",
            semanticKey: "joyful-down-right",
            headX: -36.2, headY: 13.1, headZ: 15.5,
            widthLeft: 44.3, widthRight: 51.3,
            heightLeft: 74.2, heightRight: 76,
            spacing: 68.7,
            positionXLeft: 0, positionXRight: 0,
            positionYLeft: -40.7, positionYRight: -40.7,
            leftAngle: 0, rightAngle: 0,
            perspective: 1
        ),
        AvatarLabExpression(
            id: "expression-03",
            semanticKey: "surprised-left",
            headX: 15.6, headY: -16.5, headZ: -11.3,
            widthLeft: 54, widthRight: 51,
            heightLeft: 49.6, heightRight: 48.5,
            spacing: 70.9,
            positionXLeft: 0, positionXRight: 0,
            positionYLeft: 30.1, positionYRight: 30.1,
            leftAngle: 0, rightAngle: 0,
            perspective: 1
        ),
        AvatarLabExpression(
            id: "expression-04",
            semanticKey: "sleepy-squint",
            headX: 3.4, headY: 13, headZ: 8.9,
            widthLeft: 42.6, widthRight: 44,
            heightLeft: 17.3, heightRight: 16,
            spacing: 57.9,
            positionXLeft: 0, positionXRight: 0,
            positionYLeft: 4.9, positionYRight: 4.9,
            leftAngle: 0, rightAngle: 0,
            perspective: 1
        ),
        AvatarLabExpression(
            id: "expression-05",
            semanticKey: "skeptical-right",
            headX: -17.7, headY: -1.4, headZ: -8.8,
            widthLeft: 29.5, widthRight: 19.2,
            heightLeft: 51.6, heightRight: 41.9,
            spacing: 56.3,
            positionXLeft: 0, positionXRight: 0,
            positionYLeft: 0, positionYRight: 0,
            leftAngle: 0, rightAngle: 90,
            perspective: 1
        ),
        AvatarLabExpression(
            id: "expression-06",
            semanticKey: "small-attentive",
            headX: 14.8, headY: 14.5, headZ: 5.5,
            widthLeft: 22.9, widthRight: 22.2,
            heightLeft: 32.4, heightRight: 33.4,
            spacing: 50.9,
            positionXLeft: 0, positionXRight: 0,
            positionYLeft: 39.2, positionYRight: 39.2,
            leftAngle: 0, rightAngle: 0,
            perspective: 1
        ),
        AvatarLabExpression(
            id: "expression-07",
            semanticKey: "angry-right",
            headX: 25.7, headY: 16.5, headZ: -13.5,
            widthLeft: 48.5, widthRight: 48.3,
            heightLeft: 33.5, heightRight: 33,
            spacing: 53.3,
            positionXLeft: 0, positionXRight: 0,
            positionYLeft: 41.3, positionYRight: 41.3,
            leftAngle: 61.3, rightAngle: -80,
            perspective: 1
        ),
        AvatarLabExpression(
            id: "expression-08",
            semanticKey: "curious-left",
            headX: -22.8, headY: -15.9, headZ: 6.2,
            widthLeft: 44.5, widthRight: 43.9,
            heightLeft: 32.3, heightRight: 24.6,
            spacing: 54.9,
            positionXLeft: 0, positionXRight: 0,
            positionYLeft: -42, positionYRight: -42,
            leftAngle: -60.9, rightAngle: 69.2,
            perspective: 1
        ),
        AvatarLabExpression(
            id: "expression-09",
            semanticKey: "asymmetric-down-right",
            headX: -11.6, headY: 8.3, headZ: -12.7,
            widthLeft: 42.5, widthRight: 22.1,
            heightLeft: 41.8, heightRight: 22.2,
            spacing: 61.7,
            positionXLeft: 0, positionXRight: 0,
            positionYLeft: 12.3, positionYRight: 12.3,
            leftAngle: 0, rightAngle: 0,
            perspective: 1
        ),
        AvatarLabExpression(
            id: "expression-10",
            semanticKey: "attentive-left",
            headX: 20.3, headY: 7, headZ: 8.7,
            widthLeft: 30.2, widthRight: 28.1,
            heightLeft: 48.8, heightRight: 49.2,
            spacing: 56.8,
            positionXLeft: 0, positionXRight: 0,
            positionYLeft: 39.9, positionYRight: 39.9,
            leftAngle: 0, rightAngle: 0,
            perspective: 1
        ),
        AvatarLabExpression(
            id: "expression-11",
            semanticKey: "joyful-wide",
            headX: 17.5, headY: -15.2, headZ: -8.7,
            widthLeft: 51, widthRight: 49.2,
            heightLeft: 75.3, heightRight: 73.4,
            spacing: 70.2,
            positionXLeft: 0, positionXRight: 0,
            positionYLeft: 41.6, positionYRight: 41.6,
            leftAngle: 0, rightAngle: 0,
            perspective: 1
        ),
        AvatarLabExpression(
            id: "expression-12",
            semanticKey: "wide-downward-gaze",
            headX: -10.4, headY: 15.2, headZ: 11.8,
            widthLeft: 50.6, widthRight: 51.6,
            heightLeft: 50, heightRight: 50.7,
            spacing: 69.5,
            positionXLeft: 0, positionXRight: 0,
            positionYLeft: 16.7, positionYRight: 16.7,
            leftAngle: 0, rightAngle: 0,
            perspective: 1
        ),
        AvatarLabExpression(
            id: "expression-13",
            semanticKey: "eyes-closed",
            headX: -6, headY: -7.7, headZ: -9.4,
            widthLeft: 43.6, widthRight: 42.8,
            heightLeft: 15.5, heightRight: 18.1,
            spacing: 57.9,
            positionXLeft: 0, positionXRight: 0,
            positionYLeft: 3.5, positionYRight: 3.5,
            leftAngle: 0, rightAngle: 0,
            perspective: 1
        ),
        AvatarLabExpression(
            id: "expression-14",
            semanticKey: "skeptical-left",
            headX: 0.2, headY: -3.1, headZ: 9,
            widthLeft: 29.6, widthRight: 16.8,
            heightLeft: 51.5, heightRight: 41.3,
            spacing: 56.4,
            positionXLeft: 0, positionXRight: 0,
            positionYLeft: -7.8, positionYRight: -7.8,
            leftAngle: 0, rightAngle: 90,
            perspective: 1
        ),
        AvatarLabExpression(
            id: "expression-15",
            semanticKey: "far-right-glance",
            headX: -16.2, headY: 38.4, headZ: 2.4,
            widthLeft: 23.7, widthRight: 26.2,
            heightLeft: 32.7, heightRight: 34.6,
            spacing: 53.9,
            positionXLeft: 0, positionXRight: 0,
            positionYLeft: -41.1, positionYRight: -41.1,
            leftAngle: 0, rightAngle: 0,
            perspective: 1
        ),
        AvatarLabExpression(
            id: "expression-16",
            semanticKey: "angry-left",
            headX: 3.5, headY: -16.1, headZ: 15.8,
            widthLeft: 51, widthRight: 48.5,
            heightLeft: 34.9, heightRight: 33,
            spacing: 55.1,
            positionXLeft: 0, positionXRight: 0,
            positionYLeft: 41.9, positionYRight: 41.9,
            leftAngle: 80, rightAngle: -62.2,
            perspective: 1
        ),
        AvatarLabExpression(
            id: "expression-17",
            semanticKey: "playful-right",
            headX: -17.3, headY: 11.2, headZ: -9.1,
            widthLeft: 24.2, widthRight: 44.5,
            heightLeft: 44.5, heightRight: 32.2,
            spacing: 55,
            positionXLeft: 0, positionXRight: 0,
            positionYLeft: -36.5, positionYRight: -36.5,
            leftAngle: 18.5, rightAngle: 67.9,
            perspective: 1
        ),
        AvatarLabExpression(
            id: "expression-18",
            semanticKey: "asymmetric-up-left",
            headX: -0.7, headY: 3.6, headZ: 12.2,
            widthLeft: 42.1, widthRight: 22.2,
            heightLeft: 41.7, heightRight: 22.1,
            spacing: 60.4,
            positionXLeft: 0, positionXRight: 0,
            positionYLeft: -9.1, positionYRight: -9.1,
            leftAngle: 0, rightAngle: 0,
            perspective: 1
        ),
        AvatarLabExpression(
            id: "expression-19",
            semanticKey: "gentle-downward-gaze",
            headX: -25.3, headY: -12.4, headZ: -13.3,
            widthLeft: 30.5, widthRight: 26.8,
            heightLeft: 49.9, heightRight: 48.8,
            spacing: 56.2,
            positionXLeft: 0, positionXRight: 0,
            positionYLeft: -35.8, positionYRight: -35.8,
            leftAngle: 0, rightAngle: 0,
            perspective: 1
        ),
        AvatarLabExpression(
            id: "expression-20",
            semanticKey: "wide-down-left",
            headX: -41.1, headY: 20.2, headZ: 18.8,
            widthLeft: 44.6, widthRight: 53,
            heightLeft: 74.9, heightRight: 77.8,
            spacing: 70.8,
            positionXLeft: 0, positionXRight: 0,
            positionYLeft: -40.6, positionYRight: -40.6,
            leftAngle: 0, rightAngle: 0,
            perspective: 1
        ),
        AvatarLabExpression(
            id: "expression-21",
            semanticKey: "surprised-wide-left",
            headX: -14.6, headY: -12.5, headZ: -16.1,
            widthLeft: 51.4, widthRight: 50.5,
            heightLeft: 50.1, heightRight: 49.4,
            spacing: 69,
            positionXLeft: 0, positionXRight: 0,
            positionYLeft: -20, positionYRight: -20,
            leftAngle: 0, rightAngle: 0,
            perspective: 1
        ),
        AvatarLabExpression(
            id: "expression-22",
            semanticKey: "drowsy-closed",
            headX: 10, headY: 2.7, headZ: 8.8,
            widthLeft: 42.9, widthRight: 43.3,
            heightLeft: 16.4, heightRight: 17.8,
            spacing: 57.9,
            positionXLeft: 0, positionXRight: 0,
            positionYLeft: 2.7, positionYRight: 2.7,
            leftAngle: 0, rightAngle: 0,
            perspective: 1
        ),
        AvatarLabExpression(
            id: "expression-23",
            semanticKey: "suspicious-right",
            headX: -17.8, headY: 10, headZ: -6.3,
            widthLeft: 28.8, widthRight: 17.3,
            heightLeft: 51.4, heightRight: 42.7,
            spacing: 56.6,
            positionXLeft: 0, positionXRight: 0,
            positionYLeft: -9.8, positionYRight: -9.8,
            leftAngle: 0, rightAngle: 90,
            perspective: 1
        ),
        AvatarLabExpression(
            id: "expression-24",
            semanticKey: "shy-downward",
            headX: -29.6, headY: 7.5, headZ: 10.1,
            widthLeft: 21.5, widthRight: 23.2,
            heightLeft: 32, heightRight: 33.5,
            spacing: 51.2,
            positionXLeft: 0, positionXRight: 0,
            positionYLeft: -37.4, positionYRight: -37.4,
            leftAngle: 0, rightAngle: 0,
            perspective: 1
        ),
    ]

    /// avatar-lab's `defaultExpression`: a straight-on face, and the fallback
    /// for a step whose expression cannot be resolved.
    public static let neutral = AvatarLabExpression(
        id: "expression-neutral",
        semanticKey: "neutral",
        headX: 0,
        headY: 0,
        headZ: 0,
        widthLeft: 20,
        widthRight: 20,
        heightLeft: 50,
        heightRight: 50,
        spacing: 35,
        positionXLeft: 0,
        positionXRight: 0,
        positionYLeft: -7,
        positionYRight: -7,
        leftAngle: 0,
        rightAngle: 0,
        perspective: 1
    )

    /// Every preset, the neutral one included, keyed by id.
    public static let expressionsByID: [String: AvatarLabExpression] = Dictionary(
        uniqueKeysWithValues: (expressions + [neutral]).map { ($0.id, $0) }
    )

    /// The built-in animations, as `createInitialSequences()` derives them
    /// from the pools and the per-state playback config.
    public static let sequences: [AvatarSequence] = [
        AvatarSequence(
            id: .sleeping,
            group: .lifeCycle,
            playback: .loop,
            steps: [
                AvatarSequenceStep(expressionID: "expression-13", hold: 3.6, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-22", hold: 3.6, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-04", hold: 3.6, transition: 0.5, curve: .smooth),
            ],
            blink: AvatarBlinkRhythm(
                isEnabled: true,
                initialDelay: 4.8,
                minInterval: 6.5,
                maxInterval: 9.5,
                duration: 0.42
            )
        ),
        AvatarSequence(
            id: .waking,
            group: .lifeCycle,
            playback: .loop,
            steps: [
                AvatarSequenceStep(expressionID: "expression-13", hold: 2.3, transition: 0.5, curve: .smooth),
            ],
            blink: AvatarBlinkRhythm(
                isEnabled: true,
                initialDelay: 1.2,
                minInterval: 1.8,
                maxInterval: 3.6,
                duration: 0.22
            )
        ),
        AvatarSequence(
            id: .idle,
            group: .lifeCycle,
            playback: .loop,
            steps: [
                AvatarSequenceStep(expressionID: "expression-00", hold: 5.2, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-08", hold: 5.2, transition: 0.5, curve: .smooth),
            ],
            blink: AvatarBlinkRhythm(
                isEnabled: true,
                initialDelay: 2.6,
                minInterval: 3.4,
                maxInterval: 6.2,
                duration: 0.28
            )
        ),
        AvatarSequence(
            id: .listening,
            group: .lifeCycle,
            playback: .loop,
            steps: [
                AvatarSequenceStep(expressionID: "expression-10", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-01", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-19", hold: 2.3, transition: 0.5, curve: .smooth),
            ],
            blink: AvatarBlinkRhythm(
                isEnabled: true,
                initialDelay: 3.2,
                minInterval: 4.8,
                maxInterval: 7.2,
                duration: 0.24
            )
        ),
        AvatarSequence(
            id: .thinking,
            group: .lifeCycle,
            playback: .loop,
            steps: [
                AvatarSequenceStep(expressionID: "expression-08", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-16", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-14", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-17", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-05", hold: 2.3, transition: 0.5, curve: .smooth),
            ],
            blink: AvatarBlinkRhythm(
                isEnabled: true,
                initialDelay: 2.1,
                minInterval: 2.8,
                maxInterval: 5,
                duration: 0.26
            )
        ),
        AvatarSequence(
            id: .searching,
            group: .lifeCycle,
            playback: .loop,
            steps: [
                AvatarSequenceStep(expressionID: "expression-15", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-09", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-03", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-20", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-12", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-18", hold: 2.3, transition: 0.5, curve: .smooth),
            ],
            blink: AvatarBlinkRhythm(
                isEnabled: true,
                initialDelay: 2.1,
                minInterval: 2.8,
                maxInterval: 5,
                duration: 0.26
            )
        ),
        AvatarSequence(
            id: .working,
            group: .lifeCycle,
            playback: .loop,
            steps: [
                AvatarSequenceStep(expressionID: "expression-07", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-16", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-11", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-10", hold: 2.3, transition: 0.5, curve: .smooth),
            ],
            blink: AvatarBlinkRhythm(
                isEnabled: true,
                initialDelay: 2.1,
                minInterval: 2.8,
                maxInterval: 5,
                duration: 0.26
            )
        ),
        AvatarSequence(
            id: .excited,
            group: .reaction,
            playback: .loop,
            steps: [
                AvatarSequenceStep(expressionID: "expression-02", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-17", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-21", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-03", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-11", hold: 2.3, transition: 0.5, curve: .smooth),
            ],
            blink: AvatarBlinkRhythm(
                isEnabled: true,
                initialDelay: 1.2,
                minInterval: 1.8,
                maxInterval: 3.6,
                duration: 0.22
            )
        ),
        AvatarSequence(
            id: .surprised,
            group: .reaction,
            playback: .loop,
            steps: [
                AvatarSequenceStep(expressionID: "expression-03", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-21", hold: 2.3, transition: 0.5, curve: .smooth),
            ],
            blink: AvatarBlinkRhythm(
                isEnabled: true,
                initialDelay: 1.2,
                minInterval: 1.8,
                maxInterval: 3.6,
                duration: 0.22
            )
        ),
        AvatarSequence(
            id: .suspicious,
            group: .reaction,
            playback: .loop,
            steps: [
                AvatarSequenceStep(expressionID: "expression-14", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-05", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-23", hold: 2.3, transition: 0.5, curve: .smooth),
            ],
            blink: AvatarBlinkRhythm(
                isEnabled: true,
                initialDelay: 2.1,
                minInterval: 2.8,
                maxInterval: 5,
                duration: 0.26
            )
        ),
        AvatarSequence(
            id: .angry,
            group: .reaction,
            playback: .loop,
            steps: [
                AvatarSequenceStep(expressionID: "expression-07", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-16", hold: 2.3, transition: 0.5, curve: .smooth),
            ],
            blink: AvatarBlinkRhythm(
                isEnabled: true,
                initialDelay: 2.1,
                minInterval: 2.8,
                maxInterval: 5,
                duration: 0.26
            )
        ),
        AvatarSequence(
            id: .drowsy,
            group: .reaction,
            playback: .loop,
            steps: [
                AvatarSequenceStep(expressionID: "expression-04", hold: 3.6, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-22", hold: 3.6, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-13", hold: 3.6, transition: 0.5, curve: .smooth),
            ],
            blink: AvatarBlinkRhythm(
                isEnabled: true,
                initialDelay: 4.8,
                minInterval: 6.5,
                maxInterval: 9.5,
                duration: 0.42
            )
        ),
        AvatarSequence(
            id: .happy,
            group: .reaction,
            playback: .loop,
            steps: [
                AvatarSequenceStep(expressionID: "expression-02", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-11", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-17", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-19", hold: 2.3, transition: 0.5, curve: .smooth),
            ],
            blink: AvatarBlinkRhythm(
                isEnabled: true,
                initialDelay: 2.1,
                minInterval: 2.8,
                maxInterval: 5,
                duration: 0.26
            )
        ),
        AvatarSequence(
            id: .curious,
            group: .reaction,
            playback: .loop,
            steps: [
                AvatarSequenceStep(expressionID: "expression-03", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-21", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-00", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-15", hold: 2.3, transition: 0.5, curve: .smooth),
            ],
            blink: AvatarBlinkRhythm(
                isEnabled: true,
                initialDelay: 2.1,
                minInterval: 2.8,
                maxInterval: 5,
                duration: 0.26
            )
        ),
        AvatarSequence(
            id: .confused,
            group: .reaction,
            playback: .loop,
            steps: [
                AvatarSequenceStep(expressionID: "expression-14", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-05", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-08", hold: 2.3, transition: 0.5, curve: .smooth),
            ],
            blink: AvatarBlinkRhythm(
                isEnabled: true,
                initialDelay: 2.1,
                minInterval: 2.8,
                maxInterval: 5,
                duration: 0.26
            )
        ),
        AvatarSequence(
            id: .bored,
            group: .reaction,
            playback: .loop,
            steps: [
                AvatarSequenceStep(expressionID: "expression-04", hold: 3.6, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-22", hold: 3.6, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-00", hold: 3.6, transition: 0.5, curve: .smooth),
            ],
            blink: AvatarBlinkRhythm(
                isEnabled: true,
                initialDelay: 4.8,
                minInterval: 6.5,
                maxInterval: 9.5,
                duration: 0.42
            )
        ),
        AvatarSequence(
            id: .proud,
            group: .reaction,
            playback: .loop,
            steps: [
                AvatarSequenceStep(expressionID: "expression-15", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-08", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-02", hold: 2.3, transition: 0.5, curve: .smooth),
            ],
            blink: AvatarBlinkRhythm(
                isEnabled: true,
                initialDelay: 2.1,
                minInterval: 2.8,
                maxInterval: 5,
                duration: 0.26
            )
        ),
        AvatarSequence(
            id: .shy,
            group: .reaction,
            playback: .loop,
            steps: [
                AvatarSequenceStep(expressionID: "expression-00", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-24", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-13", hold: 2.3, transition: 0.5, curve: .smooth),
            ],
            blink: AvatarBlinkRhythm(
                isEnabled: true,
                initialDelay: 2.1,
                minInterval: 2.8,
                maxInterval: 5,
                duration: 0.26
            )
        ),
        AvatarSequence(
            id: .sad,
            group: .reaction,
            playback: .loop,
            steps: [
                AvatarSequenceStep(expressionID: "expression-04", hold: 3.6, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-13", hold: 3.6, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-22", hold: 3.6, transition: 0.5, curve: .smooth),
            ],
            blink: AvatarBlinkRhythm(
                isEnabled: true,
                initialDelay: 4.8,
                minInterval: 6.5,
                maxInterval: 9.5,
                duration: 0.42
            )
        ),
        AvatarSequence(
            id: .laughing,
            group: .reaction,
            playback: .loop,
            steps: [
                AvatarSequenceStep(expressionID: "expression-02", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-11", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-17", hold: 2.3, transition: 0.5, curve: .smooth),
            ],
            blink: AvatarBlinkRhythm(
                isEnabled: true,
                initialDelay: 1.2,
                minInterval: 1.8,
                maxInterval: 3.6,
                duration: 0.22
            )
        ),
        AvatarSequence(
            id: .scared,
            group: .reaction,
            playback: .loop,
            steps: [
                AvatarSequenceStep(expressionID: "expression-03", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-21", hold: 2.3, transition: 0.5, curve: .smooth),
            ],
            blink: AvatarBlinkRhythm(
                isEnabled: true,
                initialDelay: 1.2,
                minInterval: 1.8,
                maxInterval: 3.6,
                duration: 0.22
            )
        ),
        AvatarSequence(
            id: .playful,
            group: .reaction,
            playback: .loop,
            steps: [
                AvatarSequenceStep(expressionID: "expression-02", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-17", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-11", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-08", hold: 2.3, transition: 0.5, curve: .smooth),
            ],
            blink: AvatarBlinkRhythm(
                isEnabled: true,
                initialDelay: 2.1,
                minInterval: 2.8,
                maxInterval: 5,
                duration: 0.26
            )
        ),
        AvatarSequence(
            id: .celebrate,
            group: .reaction,
            playback: .loop,
            steps: [
                AvatarSequenceStep(expressionID: "expression-02", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-08", hold: 2.3, transition: 0.5, curve: .smooth),
                AvatarSequenceStep(expressionID: "expression-17", hold: 2.3, transition: 0.5, curve: .smooth),
            ],
            blink: AvatarBlinkRhythm(
                isEnabled: true,
                initialDelay: 1.2,
                minInterval: 1.8,
                maxInterval: 3.6,
                duration: 0.22
            )
        ),
    ]

    public static let sequencesByID: [AvatarSequenceID: AvatarSequence] = Dictionary(
        uniqueKeysWithValues: sequences.map { ($0.id, $0) }
    )

    /// The sequence for an id. Total by construction — every case of
    /// ``AvatarSequenceID`` is generated from the table above — and a test
    /// pins that.
    public static func sequence(_ id: AvatarSequenceID) -> AvatarSequence {
        sequencesByID[id] ?? sequences[0]
    }
}
